---
pkgs:
  - aptitude
  - vim
  - kmod
  - iptables-persistent
  - build-essential
  - nodejs
  - git
  - htop
  - vnstat
  - nload
  - netcat-openbsd
  - node-redis
  - python-redis
  - python3-requests
